### ISSUE TITLE
epic: funding rate bot [internship subproject]

### ISSUE THREAD

**Issue by Unique-Divine** [NibiruChain/py-sdk#248]
## Context

Bot that runs and holds open positions in an attempt to profit from funding payments.

> **Note**
> This epic was moved into Golang as [NibiruChain/fbot](https://github.com/NibiruChain/fbot)

# Task List 

## epic: init

- [x] Address 2023-07-18 review comments on the [draft PR of the MVP](https://github.com/NibiruChain/py-sdk/pull/247)
- Prefer `logging` functions over `print`
- [x] test [parsing of the markets query](https://github.com/NibiruChain/py-sdk/pull/247#discussion_r1267313391)
- [ ] Add option to write the logs to a file in "append mode". 
- [x] refactor: Convert the bot to Golang for easier re-use and testing

## epic: Use `sqlite3` rather than dictionaries in memory.  

- [x] Write function for storing the result of the positions query
- [x] test ↑
- [x] Write function for storing the result of the oracle prices query
- [x] test ↑
- [x] Write function grabbing a collection of positions from the table
- [x] test ↑
- [x] Write function grabbing a collection of "trade reports" from the table
- [x] test ↑

## NibiruCHain/fbot Tracking

- [ ] test `should_make_position`

**Comment by Unique-Divine** [comment]
Out of scope for current goals
