### ISSUE TITLE
epic: logging

### ISSUE THREAD

**Issue by Unique-Divine** [NibiruChain/py-sdk#71]
perp commands: 
- [x] logging on `tx perp open-position` and its response
- [x] logging on `tx perp close-position` and its response
- [x] logging on `tx perp add-margin`
- [x] logging on `tx perp remove-margin`

other commands:
- [x] logging on `tx pricefeed`
- [x] logging on `tx bank`

else:
- [x] docs: Usage instructions on logging the code
- [x] feat: Add colored logging using only the standard library.
